const developer = (prefix) => { 

	return `

╭──────「 *ABOUT CREATOR* 」
┴
ASSALAMUALAIKUM TEMAN TEMAN, BUAT KALIAN SEMUA YANG DARI GITHUB , TERIMAKASIH BANYAK UDAH SUPPORT SAMPAI SEJAUH INI. 

SINGKAT PENJELASAN AJA, BUAT KALIAN YANG INGIN AMBIL CASE TOLONG IZIN, DAN BUAT KALIAN REMAKE HINGGA SEMUANYA DI UBAH, TOLONG JANGAN SEPERTI ITU, JANGAN HILANGKAN SAYA DALAM DATABASE SCRIPT BOT WHATSAPP, DAN JANGAN HILANGKAN JUGA CREDIT CREATOR-CREATOR SANAD KARANGAN SCRIPT WHATSAPP BOT SEBELUMNYA.MUNGKIN  ITU AJA YANG AKU SAMPAIKAN, DI BAWAH INI ADA BEBERAPA INFO TENTANG AKU

● *SOSIAL MEDIA :*


INI INSTAGRAM AKU
https://www.instagram.com/_agoeng_2
WHATSAPP AKU
082181347492



*DONASI :*

 اتَّقوا النَّارَ ولو بشقِّ تمرةٍ ، فمن لم يجِدْ فبكلمةٍ طيِّبةٍ
_“jauhilah api neraka, walau hanya dengan bersedekah sebiji kurma (sedikit). Jika kamu tidak punya, maka bisa dengan kalimah thayyibah” [HR. Bukhari 6539, Muslim 1016]_

VIA LINK SAWERIA
https://saweria.co/agung22
VIA DANA
0821-8134-7492
VIA OVO
0821-8134-7492
VIA GOPAY
0821-8134-7492

*BEBAS KALIAN MAU DONASI BERAPA, SEMOGA KALIAN SEMUA DI MUDAHKAN REZEKINYA AAMIIN*`

}

exports.developer = developer